export const UserTypes = {
  FAMILY: 'FAMILY',
  LOCAL_COORDINATOR: 'LOCAL_COORDINATOR',
  NOT_DEFINED: 'NOT_DEFINED',
  SUPER_USER: 'SUPER_USER',
  SEARCHER: 'SEARCHER',
}

export const FamilyScores = {
  NOT_DEFINED: 'NOT_DEFINED',
  GOLD: 'GOLD',
  SILVER: 'SILVER',
  BRONZE: 'BRONZE',
}

export const FamilyStatusOptions = {
  POTENTIAL: 'POTENTIAL',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  REJECTED: 'REJECTED',
  REMOVED: 'REMOVED',
}
