name: Red Leaf QA Admin Deploy
on:
  push:
    branches: [ testing ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install NPM Dependencies
        run: npm install
      - name: Serverless AWS Authentication
        run: sls config credentials --provider aws --key %{{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Move into right environment
        run: cd ./environments/testing && serverless
